[build]
  publish = "src"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/llm"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
